name: Seeed reTerminal buildroot
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1,2,3,4,5
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install sed make binutils build-essential gcc g++ bash patch \
          gzip bzip2 perl tar cpio unzip rsync file bc wget python cvs git \
          mercurial subversion libfontconfig1 fontconfig libfontconfig1-dev \
          fontconfig-config libxi-dev libaudio-dev libxrender-dev
          
      - name: Checkout Buildroot sources
        run: git clone --depth=1 -b master https://github.com/Seeed-Studio/seeed-linux-buildroot.git

      - name: Seeed buildroot cache
        uses: actions/cache@v3
        env:
          cache-name: cache-download-files
        with:
          path: ${{ github.workspace }}/seeed-linux-buildroot/dl/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/seeed-linux-buildroot/configs/reTerminal_64_defconfig') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        
      - name: Configure Buildroot
        run: |
          cd ${{ github.workspace }}/seeed-linux-buildroot/
          make reTerminal_64_defconfig

      - name: Build
        run: |
          cd ${{ github.workspace }}/seeed-linux-buildroot/
          make

      - name: Pack
        run: |
          cd ${{ github.workspace }}/seeed-linux-buildroot/output/images/
          tar -zcvf buildroot-image.tar.gz sdcard.img
          echo "PACKAGE=${{ github.workspace }}/seeed-linux-buildroot/output/images/buildroot-image.tar.gz" >> $GITHUB_ENV

      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: buildroot deploy
          path: ${{env.PACKAGE}}
